pipeline:
  git_diff:
    image: alpine/git
    commands:
      - git show

  js_lint:
    image: alpine
    commands:
      - apk add jq
      - jq '.' test.json

  html_validator:
    image: python:alpine
    commands:
      - pwd
      - wget https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py
      - ls *.html | xargs -I {} ash -c 'echo -- {}; python html5check.py -h {}; echo'
