pipeline:
  git_diff:
    image: alpine/git
    commands:
      - git show

  js_lint:
    image: alpine
    commands:
      - apk add jq
      - jq '.' test.json

  html_validator:
    image: validator/validator
    commands:
      - java -jar /vnu.jar \*.html
